-- =========================================================
-- PETCORE - SCRIPT DE BANCO DE DADOS
-- Oracle Database
-- Sprint DevOps Tools & Cloud Computing
-- =========================================================

-- 1. REMOCAO DAS TABELAS
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE cli_rel_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE rec_medic_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tut_pet_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE exame_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE receita_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE prontuario_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE relatorio_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE pet_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE historico_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE clinica_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE endereco_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE medicamento_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE tutor_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE medico_petcore CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- =========================================================
-- 2. CRIACAO DAS TABELAS
-- =========================================================

create table tutor_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    data_nascimento date,
    telefone VARCHAR2(11) not null,
    email VARCHAR2(100) not null,
    sexo VARCHAR2(1) not null,
    senha VARCHAR2(100) not null,
    url_img VARCHAR2(255),
    primary key (id)
);

create table medico_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    data_nascimento date,
    telefone VARCHAR2(11) not null,
    email VARCHAR2(100) not null,
    sexo VARCHAR2(1) not null,
    senha VARCHAR2(100) not null,
    especialidade VARCHAR2(200) not null,
    url_img VARCHAR2(255),
    primary key (id)
);

create table historico_petcore (
    id NUMBER generated by default as identity,
    data timestamp,
    status NUMBER(1),
    primary key (id)
);

create table pet_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    especie VARCHAR2(100) not null,
    raca VARCHAR2(150) not null,
    data_nascimento date,
    pelagem VARCHAR2(150) not null,
    porte VARCHAR2(25) not null,
    sexo VARCHAR2(1) not null,
    status NUMBER(1),
    url_img VARCHAR2(255),
    "ID_hist_(FK)" NUMBER,
    primary key (id)
);

create table endereco_petcore (
    id NUMBER generated by default as identity,
    cep VARCHAR2(8) not null,
    complemento VARCHAR2(200),
    primary key (id)
);

create table clinica_petcore (
    id NUMBER generated by default as identity,
    cnpj VARCHAR2(14) not null,
    nome VARCHAR2(100) not null,
    "ID_end_(FK)" NUMBER not null,
    primary key (id)
);

create table medicamento_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    dosagem VARCHAR2(15) not null,
    primary key (id)
);

create table prontuario_petcore (
    id NUMBER generated by default as identity,
    data timestamp not null,
    descricao VARCHAR2(500) not null,
    "ID_med_(PK)" NUMBER not null,
    "ID_hist_(PK)" NUMBER not null,
    primary key (id)
);

create table exame_petcore (
    id NUMBER generated by default as identity,
    nome_ex VARCHAR2(100) not null,
    data timestamp,
    tp_ex VARCHAR2(100) not null,
    removido NUMBER(1) default 0 not null,
    "ID_med_(PK)" NUMBER not null,
    "ID_pront_(PK)" NUMBER,
    "ID_pet_(FK)" NUMBER not null,
    primary key (id),
    constraint ck_exame_removido check (removido in (0,1))
);

create table receita_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    descricao VARCHAR2(500) not null,
    instrucao VARCHAR2(200) not null,
    data timestamp not null,
    validade date,
    removida NUMBER(1) default 0 not null,
    "ID_med_(PK)" NUMBER not null,
    "ID_pront_(PK)" NUMBER,
    "ID_pet_(FK)" NUMBER not null,
    primary key (id),
    constraint ck_receita_removida check (removida in (0,1))
);

create table relatorio_petcore (
    id NUMBER generated by default as identity,
    observacao VARCHAR2(500),
    data timestamp not null,
    "ID_hist_(PK)" NUMBER not null,
    "ID_med_(PK)" NUMBER not null,
    primary key (id)
);

create table tut_pet_petcore (
    "ID_tut_(FK)" NUMBER not null,
    "ID_pet_(FK)" NUMBER not null,
    primary key ("ID_tut_(FK)", "ID_pet_(FK)")
);

create table rec_medic_petcore (
    "ID_rec_(FK)" NUMBER not null,
    "ID_medic_(FK)" NUMBER not null,
    primary key ("ID_rec_(FK)", "ID_medic_(FK)")
);

create table cli_rel_petcore (
    "ID_cli_(FK)" NUMBER not null,
    "ID_rel_(FK)" NUMBER not null,
    primary key ("ID_cli_(FK)", "ID_rel_(FK)")
);

-- =========================================================
-- 3. CONSTRAINTS
-- =========================================================

alter table tutor_petcore add constraint uk_tutor_email unique (email);
alter table tutor_petcore add constraint uk_tutor_telefone unique (telefone);
alter table medico_petcore add constraint uk_medico_email unique (email);
alter table medico_petcore add constraint uk_medico_telefone unique (telefone);
alter table clinica_petcore add constraint uk_clinica_cnpj unique (cnpj);
alter table pet_petcore add constraint uk_pet_historico unique ("ID_hist_(FK)");
alter table clinica_petcore add constraint uk_clinica_endereco unique ("ID_end_(FK)");

alter table pet_petcore add constraint fk_pet_historico
    foreign key ("ID_hist_(FK)") references historico_petcore(id);
alter table clinica_petcore add constraint fk_clinica_endereco
    foreign key ("ID_end_(FK)") references endereco_petcore(id);
alter table prontuario_petcore add constraint fk_prontuario_medico
    foreign key ("ID_med_(PK)") references medico_petcore(id);
alter table prontuario_petcore add constraint fk_prontuario_historico
    foreign key ("ID_hist_(PK)") references historico_petcore(id);
alter table exame_petcore add constraint fk_exame_medico
    foreign key ("ID_med_(PK)") references medico_petcore(id);
alter table exame_petcore add constraint fk_exame_prontuario
    foreign key ("ID_pront_(PK)") references prontuario_petcore(id);
alter table exame_petcore add constraint fk_exame_pet
    foreign key ("ID_pet_(FK)") references pet_petcore(id);
alter table receita_petcore add constraint fk_receita_medico
    foreign key ("ID_med_(PK)") references medico_petcore(id);
alter table receita_petcore add constraint fk_receita_prontuario
    foreign key ("ID_pront_(PK)") references prontuario_petcore(id);
alter table receita_petcore add constraint fk_receita_pet
    foreign key ("ID_pet_(FK)") references pet_petcore(id);
alter table relatorio_petcore add constraint fk_relatorio_historico
    foreign key ("ID_hist_(PK)") references historico_petcore(id);
alter table relatorio_petcore add constraint fk_relatorio_medico
    foreign key ("ID_med_(PK)") references medico_petcore(id);
alter table tut_pet_petcore add constraint fk_tut_pet_tutor
    foreign key ("ID_tut_(FK)") references tutor_petcore(id);
alter table tut_pet_petcore add constraint fk_tut_pet_pet
    foreign key ("ID_pet_(FK)") references pet_petcore(id);
alter table rec_medic_petcore add constraint fk_rec_medic_receita
    foreign key ("ID_rec_(FK)") references receita_petcore(id);
alter table rec_medic_petcore add constraint fk_rec_medic_medicamento
    foreign key ("ID_medic_(FK)") references medicamento_petcore(id);
alter table cli_rel_petcore add constraint fk_cli_rel_clinica
    foreign key ("ID_cli_(FK)") references clinica_petcore(id);
alter table cli_rel_petcore add constraint fk_cli_rel_relatorio
    foreign key ("ID_rel_(FK)") references relatorio_petcore(id);

alter table tutor_petcore add constraint ck_tutor_sexo check (sexo in ('F','M'));
alter table medico_petcore add constraint ck_medico_sexo check (sexo in ('F','M'));
alter table pet_petcore add constraint ck_pet_sexo check (sexo in ('F','M'));
alter table pet_petcore add constraint ck_pet_status check (status in (0,1));
alter table historico_petcore add constraint ck_historico_status check (status in (0,1));

-- =========================================================
-- 4. COMENTARIOS DAS TABELAS E COLUNAS
-- =========================================================

comment on table tutor_petcore is 'Armazena os tutores responsaveis pelos pets.';
comment on column tutor_petcore.id is 'Identificador unico do tutor.';
comment on column tutor_petcore.nome is 'Nome completo do tutor.';
comment on column tutor_petcore.data_nascimento is 'Data de nascimento do tutor.';
comment on column tutor_petcore.telefone is 'Telefone de contato do tutor.';
comment on column tutor_petcore.email is 'E-mail do tutor.';
comment on column tutor_petcore.sexo is 'Sexo do tutor: F ou M.';
comment on column tutor_petcore.senha is 'Senha criptografada do tutor.';
comment on column tutor_petcore.url_img is 'URL da imagem de perfil do tutor.';

comment on table medico_petcore is 'Armazena os medicos veterinarios cadastrados.';
comment on column medico_petcore.id is 'Identificador unico do medico veterinario.';
comment on column medico_petcore.nome is 'Nome completo do medico veterinario.';
comment on column medico_petcore.data_nascimento is 'Data de nascimento do medico veterinario.';
comment on column medico_petcore.telefone is 'Telefone de contato do medico veterinario.';
comment on column medico_petcore.email is 'E-mail do medico veterinario.';
comment on column medico_petcore.sexo is 'Sexo do medico veterinario: F ou M.';
comment on column medico_petcore.senha is 'Senha criptografada do medico veterinario.';
comment on column medico_petcore.especialidade is 'Especialidade do medico veterinario.';
comment on column medico_petcore.url_img is 'URL da imagem de perfil do medico veterinario.';

comment on table historico_petcore is 'Armazena historicos clinicos dos pets.';
comment on column historico_petcore.id is 'Identificador unico do historico.';
comment on column historico_petcore.data is 'Data e hora de referencia do historico.';
comment on column historico_petcore.status is 'Status do historico, representado por 0 ou 1.';

comment on table pet_petcore is 'Armazena os pets cadastrados na plataforma.';
comment on column pet_petcore.id is 'Identificador unico do pet.';
comment on column pet_petcore.nome is 'Nome do pet.';
comment on column pet_petcore.especie is 'Especie do pet.';
comment on column pet_petcore.raca is 'Raca do pet.';
comment on column pet_petcore.data_nascimento is 'Data de nascimento do pet.';
comment on column pet_petcore.pelagem is 'Descricao da pelagem do pet.';
comment on column pet_petcore.porte is 'Porte do pet.';
comment on column pet_petcore.sexo is 'Sexo do pet: F ou M.';
comment on column pet_petcore.status is 'Status do pet, representado por 0 ou 1.';
comment on column pet_petcore.url_img is 'URL da imagem do pet.';
comment on column pet_petcore."ID_hist_(FK)" is 'Referencia opcional ao historico clinico do pet.';

comment on table endereco_petcore is 'Armazena enderecos utilizados pelas clinicas.';
comment on column endereco_petcore.id is 'Identificador unico do endereco.';
comment on column endereco_petcore.cep is 'CEP do endereco.';
comment on column endereco_petcore.complemento is 'Complemento do endereco.';

comment on table clinica_petcore is 'Armazena as clinicas veterinarias.';
comment on column clinica_petcore.id is 'Identificador unico da clinica.';
comment on column clinica_petcore.cnpj is 'CNPJ da clinica.';
comment on column clinica_petcore.nome is 'Nome da clinica.';
comment on column clinica_petcore."ID_end_(FK)" is 'Referencia ao endereco da clinica.';

comment on table medicamento_petcore is 'Armazena os medicamentos cadastrados.';
comment on column medicamento_petcore.id is 'Identificador unico do medicamento.';
comment on column medicamento_petcore.nome is 'Nome do medicamento.';
comment on column medicamento_petcore.dosagem is 'Dosagem do medicamento.';

comment on table prontuario_petcore is 'Armazena registros de prontuario veterinario.';
comment on column prontuario_petcore.id is 'Identificador unico do prontuario.';
comment on column prontuario_petcore.data is 'Data e hora do prontuario.';
comment on column prontuario_petcore.descricao is 'Descricao clinica do prontuario.';
comment on column prontuario_petcore."ID_med_(PK)" is 'Referencia ao medico responsavel.';
comment on column prontuario_petcore."ID_hist_(PK)" is 'Referencia ao historico relacionado.';

comment on table exame_petcore is 'Armazena exames dos pets.';
comment on column exame_petcore.id is 'Identificador unico do exame.';
comment on column exame_petcore.nome_ex is 'Nome do exame.';
comment on column exame_petcore.data is 'Data e hora do exame.';
comment on column exame_petcore.tp_ex is 'Tipo do exame.';
comment on column exame_petcore.removido is 'Indicador de remocao logica: 0 ou 1.';
comment on column exame_petcore."ID_med_(PK)" is 'Referencia ao medico responsavel.';
comment on column exame_petcore."ID_pront_(PK)" is 'Referencia opcional ao prontuario.';
comment on column exame_petcore."ID_pet_(FK)" is 'Referencia ao pet.';

comment on table receita_petcore is 'Armazena receitas veterinarias.';
comment on column receita_petcore.id is 'Identificador unico da receita.';
comment on column receita_petcore.nome is 'Nome ou titulo da receita.';
comment on column receita_petcore.descricao is 'Descricao do tratamento.';
comment on column receita_petcore.instrucao is 'Instrucoes da receita.';
comment on column receita_petcore.data is 'Data e hora da receita.';
comment on column receita_petcore.validade is 'Data de validade da receita.';
comment on column receita_petcore.removida is 'Indicador de remocao logica: 0 ou 1.';
comment on column receita_petcore."ID_med_(PK)" is 'Referencia ao medico responsavel.';
comment on column receita_petcore."ID_pront_(PK)" is 'Referencia opcional ao prontuario.';
comment on column receita_petcore."ID_pet_(FK)" is 'Referencia ao pet.';

comment on table relatorio_petcore is 'Armazena relatorios clinicos veterinarios.';
comment on column relatorio_petcore.id is 'Identificador unico do relatorio.';
comment on column relatorio_petcore.observacao is 'Observacoes clinicas do relatorio.';
comment on column relatorio_petcore.data is 'Data e hora do relatorio.';
comment on column relatorio_petcore."ID_hist_(PK)" is 'Referencia ao historico clinico.';
comment on column relatorio_petcore."ID_med_(PK)" is 'Referencia ao medico responsavel.';

comment on table tut_pet_petcore is 'Relaciona tutores e pets.';
comment on column tut_pet_petcore."ID_tut_(FK)" is 'Referencia ao tutor.';
comment on column tut_pet_petcore."ID_pet_(FK)" is 'Referencia ao pet.';

comment on table rec_medic_petcore is 'Relaciona receitas e medicamentos.';
comment on column rec_medic_petcore."ID_rec_(FK)" is 'Referencia a receita.';
comment on column rec_medic_petcore."ID_medic_(FK)" is 'Referencia ao medicamento.';

comment on table cli_rel_petcore is 'Relaciona clinicas e relatorios.';
comment on column cli_rel_petcore."ID_cli_(FK)" is 'Referencia a clinica.';
comment on column cli_rel_petcore."ID_rel_(FK)" is 'Referencia ao relatorio.';

-- =========================================================
-- 5. CARGA INICIAL DE DADOS
-- =========================================================

-- Senha padrao dos usuarios de teste: Petcore123
-- Hash BCrypt: $2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS


-- =========================================================
-- TUTORES
-- =========================================================

insert into tutor_petcore
(nome,data_nascimento,telefone,email,sexo,senha,url_img)
values
('Ana Souza', DATE '1991-04-12','11981000001','ana.souza@petcore.com','F',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',null);

insert into tutor_petcore
(nome,data_nascimento,telefone,email,sexo,senha,url_img)
values
('Bruno Lima', DATE '1988-11-23','11981000002','bruno.lima@petcore.com','M',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',null);

insert into tutor_petcore
(nome,data_nascimento,telefone,email,sexo,senha,url_img)
values
('Camila Rocha', DATE '1995-02-18','11981000003','camila.rocha@petcore.com','F',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',null);

insert into tutor_petcore
(nome,data_nascimento,telefone,email,sexo,senha,url_img)
values
('Diego Martins', DATE '1987-07-30','11981000004','diego.martins@petcore.com','M',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',null);

insert into tutor_petcore
(nome,data_nascimento,telefone,email,sexo,senha,url_img)
values
('Fernanda Alves', DATE '1993-09-05','11981000005','fernanda.alves@petcore.com','F',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',null);


-- =========================================================
-- MEDICOS
-- =========================================================

insert into medico_petcore
(nome,data_nascimento,telefone,email,sexo,senha,especialidade,url_img)
values
('Mariana Costa', DATE '1984-03-14','11982000001','mariana.costa@petcore.com','F',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',
'Clinica Geral',null);

insert into medico_petcore
(nome,data_nascimento,telefone,email,sexo,senha,especialidade,url_img)
values
('Beatriz Nunes', DATE '1989-06-27','11982000002','beatriz.nunes@petcore.com','F',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',
'Dermatologia Veterinaria',null);

insert into medico_petcore
(nome,data_nascimento,telefone,email,sexo,senha,especialidade,url_img)
values
('Rafael Mendes', DATE '1981-12-09','11982000003','rafael.mendes@petcore.com','M',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',
'Cardiologia Veterinaria',null);

insert into medico_petcore
(nome,data_nascimento,telefone,email,sexo,senha,especialidade,url_img)
values
('Lucas Ferreira', DATE '1986-08-16','11982000004','lucas.ferreira@petcore.com','M',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',
'Ortopedia Veterinaria',null);

insert into medico_petcore
(nome,data_nascimento,telefone,email,sexo,senha,especialidade,url_img)
values
('Juliana Prado', DATE '1990-01-21','11982000005','juliana.prado@petcore.com','F',
'$2y$10$XZG0OV7wJTj2DRVbZy/.7eIPAG.97nD2X9DaNyri.vXf2R95ry7hS',
'Diagnostico por Imagem',null);


-- =========================================================
-- HISTORICOS
-- =========================================================

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-10 09:00:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-11 10:00:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-12 11:00:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-13 09:30:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-14 14:00:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-15 15:30:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-16 08:45:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-17 13:15:00',0);

insert into historico_petcore(data,status)
values (TIMESTAMP '2026-08-18 16:20:00',0);


-- =========================================================
-- PETS
-- =========================================================

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Thor','Cachorro','Golden Retriever',DATE '2021-03-10','Dourada','GRANDE','M',0,null,1);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Mel','Cachorro','Shih Tzu',DATE '2022-07-18','Branca e marrom','PEQUENO','F',0,null,2);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Nina','Gato','Siames',DATE '2020-01-25','Clara e escura','MEDIO','F',0,null,3);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Bob','Cachorro','Beagle',DATE '2019-11-03','Tricolor','MEDIO','M',0,null,4);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Luna','Gato','Persa',DATE '2023-02-11','Cinza longa','PEQUENO','F',0,null,5);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Simba','Gato','Maine Coon',DATE '2018-06-22','Marrom longa','GRANDE','M',0,null,6);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Theo','Cachorro','Bulldog Frances',DATE '2021-09-14','Caramelo','MEDIO','M',0,null,7);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Amora','Cachorro','Border Collie',DATE '2020-05-30','Preta e branca','MEDIO','F',0,null,8);

insert into pet_petcore
(nome,especie,raca,data_nascimento,pelagem,porte,sexo,status,url_img,"ID_hist_(FK)")
values
('Bento','Cachorro','Labrador',DATE '2022-12-08','Preta curta','GRANDE','M',0,null,9);


-- =========================================================
-- RELACIONAMENTO TUTOR / PET
-- =========================================================

insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (1,1);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (1,2);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (1,3);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (2,4);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (2,5);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (3,6);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (4,7);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (5,8);
insert into tut_pet_petcore("ID_tut_(FK)","ID_pet_(FK)") values (5,9);


-- =========================================================
-- ENDERECOS
-- =========================================================

insert into endereco_petcore(cep,complemento) values ('04309010','Sala 12');
insert into endereco_petcore(cep,complemento) values ('04037002','Bloco B');
insert into endereco_petcore(cep,complemento) values ('01503001',null);
insert into endereco_petcore(cep,complemento) values ('05001000','Conjunto 51');
insert into endereco_petcore(cep,complemento) values ('03310000','Sala terrea');


-- =========================================================
-- CLINICAS
-- =========================================================

insert into clinica_petcore(cnpj,nome,"ID_end_(FK)")
values ('12345678000101','PetCare Jabaquara',1);

insert into clinica_petcore(cnpj,nome,"ID_end_(FK)")
values ('23456789000112','Vet Saude Paulista',2);

insert into clinica_petcore(cnpj,nome,"ID_end_(FK)")
values ('34567890000123','Clinica Animal Vida',3);

insert into clinica_petcore(cnpj,nome,"ID_end_(FK)")
values ('45678901000134','Centro Veterinario Oeste',4);

insert into clinica_petcore(cnpj,nome,"ID_end_(FK)")
values ('56789012000145','Pet Mais Tatuape',5);


-- =========================================================
-- MEDICAMENTOS
-- =========================================================

insert into medicamento_petcore(nome,dosagem) values ('Dipirona','500mg');
insert into medicamento_petcore(nome,dosagem) values ('Amoxicilina','250mg');
insert into medicamento_petcore(nome,dosagem) values ('Cefalexina','500mg');
insert into medicamento_petcore(nome,dosagem) values ('Prednisona','20mg');
insert into medicamento_petcore(nome,dosagem) values ('Meloxicam','2mg');
insert into medicamento_petcore(nome,dosagem) values ('Omeprazol','20mg');
insert into medicamento_petcore(nome,dosagem) values ('Doxiciclina','100mg');
insert into medicamento_petcore(nome,dosagem) values ('Metronidazol','250mg');
insert into medicamento_petcore(nome,dosagem) values ('Carprofeno','25mg');
insert into medicamento_petcore(nome,dosagem) values ('Gabapentina','100mg');


-- =========================================================
-- PRONTUARIOS
-- =========================================================

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-08-25 10:30:00',
'Consulta clinica e avaliacao dos resultados do hemograma.',1,1);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-08-27 12:00:00',
'Avaliacao dermatologica com orientacoes para tratamento de pele.',2,2);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-08-29 15:00:00',
'Avaliacao cardiologica apos realizacao de ecocardiograma.',3,3);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-09-01 11:30:00',
'Avaliacao ortopedica apos exame de imagem da pata traseira.',4,4);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-09-02 17:00:00',
'Consulta de retorno com analise do exame de ultrassom abdominal.',5,5);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-09-04 09:30:00',
'Consulta clinica para acompanhamento de alteracoes hematologicas.',1,6);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-09-05 14:00:00',
'Avaliacao ortopedica por dificuldade leve de locomocao.',4,7);

insert into prontuario_petcore(data,descricao,"ID_med_(PK)","ID_hist_(PK)")
values (TIMESTAMP '2026-09-07 16:00:00',
'Consulta preventiva e avaliacao clinica geral anual.',1,8);


-- =========================================================
-- EXAMES
-- No Oracle: false = 0
-- =========================================================

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Hemograma completo',TIMESTAMP '2026-08-25 09:00:00',
'Laboratorial',0,1,1,1);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Avaliacao dermatologica',TIMESTAMP '2026-08-27 11:00:00',
'Dermatologico',0,2,2,2);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Ecocardiograma',TIMESTAMP '2026-08-29 14:00:00',
'Cardiologico',0,3,3,3);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Radiografia da pata',TIMESTAMP '2026-09-01 10:30:00',
'Imagem',0,4,4,4);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Ultrassom abdominal',TIMESTAMP '2026-09-02 16:00:00',
'Imagem',0,5,5,5);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Hemograma de controle',TIMESTAMP '2026-09-04 08:30:00',
'Laboratorial',0,1,6,6);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Avaliacao ortopedica',TIMESTAMP '2026-09-05 13:00:00',
'Ortopedico',0,4,7,7);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Avaliacao clinica anual',TIMESTAMP '2026-09-07 15:00:00',
'Clinico Geral',0,1,8,8);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Retorno dermatologico',TIMESTAMP '2026-09-15 10:00:00',
'Dermatologico',0,2,null,9);

insert into exame_petcore
(nome_ex,data,tp_ex,removido,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values ('Ecocardiograma de retorno',TIMESTAMP '2026-09-20 09:00:00',
'Cardiologico',0,3,null,1);


-- =========================================================
-- RECEITAS
-- No Oracle: false = 0
-- =========================================================

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Tratamento pos-exame',
'Medicacao para controle de dor e prevencao de infeccao.',
'Administrar apos alimentacao.',
TIMESTAMP '2026-08-25 11:00:00',
DATE '2026-10-25',
0,1,1,1);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Tratamento dermatologico',
'Tratamento para irritacao e infeccao superficial da pele.',
'Administrar conforme orientacao medica.',
TIMESTAMP '2026-08-27 13:00:00',
DATE '2026-10-27',
0,2,2,2);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Suporte cardiologico',
'Medicacao de suporte durante acompanhamento cardiologico.',
'Administrar nos horarios prescritos.',
TIMESTAMP '2026-08-29 16:00:00',
DATE '2026-11-29',
0,3,3,3);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Controle de dor ortopedica',
'Tratamento para dor e inflamacao decorrente de lesao leve.',
'Administrar junto com alimento.',
TIMESTAMP '2026-09-01 12:00:00',
DATE '2026-10-01',
0,4,4,4);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Protecao gastrica',
'Medicacao para protecao gastrica durante o tratamento.',
'Administrar antes da primeira refeicao.',
TIMESTAMP '2026-09-02 17:30:00',
DATE '2026-10-02',
0,5,5,5);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Tratamento de controle',
'Medicacao complementar para acompanhamento hematologico.',
'Administrar uma vez ao dia.',
TIMESTAMP '2026-09-04 10:00:00',
DATE '2026-10-04',
0,1,6,6);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Tratamento ortopedico',
'Medicacao para controle de dor durante a recuperacao.',
'Administrar a cada doze horas.',
TIMESTAMP '2026-09-05 14:30:00',
DATE '2026-10-05',
0,4,7,7);

insert into receita_petcore
(nome,descricao,instrucao,data,validade,removida,"ID_med_(PK)","ID_pront_(PK)","ID_pet_(FK)")
values
('Prevencao anual',
'Medicacao preventiva apos avaliacao clinica de rotina.',
'Administrar conforme prescricao.',
TIMESTAMP '2026-09-07 16:30:00',
DATE '2026-11-07',
0,1,8,8);


-- =========================================================
-- RECEITA / MEDICAMENTO
-- =========================================================

insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (1,1);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (1,2);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (2,3);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (2,4);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (3,6);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (3,10);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (4,5);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (4,9);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (5,6);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (5,8);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (6,1);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (6,7);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (7,5);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (7,10);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (8,1);
insert into rec_medic_petcore("ID_rec_(FK)","ID_medic_(FK)") values (8,6);


-- =========================================================
-- RELATORIOS
-- =========================================================

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Animal apresentou boa resposta ao tratamento e deve manter acompanhamento de rotina.',
TIMESTAMP '2026-08-25 11:30:00',1,1);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Lesao dermatologica em melhora, mantendo tratamento e retorno programado.',
TIMESTAMP '2026-08-27 13:30:00',2,2);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Exame cardiologico sem alteracoes graves, recomendado acompanhamento periodico.',
TIMESTAMP '2026-08-29 16:30:00',3,3);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Quadro ortopedico leve e com boa evolucao durante o tratamento.',
TIMESTAMP '2026-09-01 12:30:00',4,4);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Ultrassom sem alteracoes importantes, manter acompanhamento preventivo.',
TIMESTAMP '2026-09-02 18:00:00',5,5);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Resultados laboratoriais estaveis e dentro do esperado para o acompanhamento.',
TIMESTAMP '2026-09-04 10:30:00',6,1);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Mobilidade apresentou melhora apos tratamento e periodo de repouso.',
TIMESTAMP '2026-09-05 15:00:00',7,4);

insert into relatorio_petcore
(observacao,data,"ID_hist_(PK)","ID_med_(PK)")
values
('Consulta preventiva sem alteracoes clinicas relevantes no momento.',
TIMESTAMP '2026-09-07 17:00:00',8,1);


-- =========================================================
-- CLINICA / RELATORIO
-- =========================================================

insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (1,1);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (1,6);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (2,2);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (2,8);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (3,3);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (4,4);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (4,7);
insert into cli_rel_petcore("ID_cli_(FK)","ID_rel_(FK)") values (5,5);

COMMIT;
