create table tutor_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    data_nascimento date,
    telefone VARCHAR2(11) not null,
    email VARCHAR2(100) not null,
    sexo VARCHAR2(1) not null,
    senha VARCHAR2(100) not null,
    url_img VARCHAR2(255),
    primary key (id)
);

create table medico_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    data_nascimento date,
    telefone VARCHAR2(11) not null,
    email VARCHAR2(100) not null,
    sexo VARCHAR2(1) not null,
    senha VARCHAR2(100) not null,
    especialidade VARCHAR2(200) not null,
    url_img VARCHAR2(255),
    primary key (id)
);

create table historico_petcore (
    id NUMBER generated by default as identity,
    data timestamp,
    status NUMBER(1),
    primary key (id)
);

create table pet_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    especie VARCHAR2(100) not null,
    raca VARCHAR2(150) not null,
    data_nascimento date,
    pelagem VARCHAR2(150) not null,
    porte VARCHAR2(25) not null,
    sexo VARCHAR2(1) not null,
    status NUMBER(1),
    url_img VARCHAR2(255),
    "ID_hist_(FK)" NUMBER,
    primary key (id)
);

create table endereco_petcore (
    id NUMBER generated by default as identity,
    cep VARCHAR2(8) not null,
    complemento VARCHAR2(200),
    primary key (id)
);

create table clinica_petcore (
    id NUMBER generated by default as identity,
    cnpj VARCHAR2(14) not null,
    nome VARCHAR2(100) not null,
    "ID_end_(FK)" NUMBER not null,
    primary key (id)
);

create table medicamento_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    dosagem VARCHAR2(15) not null,
    primary key (id)
);

create table prontuario_petcore (
    id NUMBER generated by default as identity,
    data timestamp not null,
    descricao VARCHAR2(500) not null,
    "ID_med_(PK)" NUMBER not null,
    "ID_hist_(PK)" NUMBER not null,
    primary key (id)
);

create table exame_petcore (
    id NUMBER generated by default as identity,
    nome_ex VARCHAR2(100) not null,
    data timestamp,
    tp_ex VARCHAR2(100) not null,
    removido NUMBER(1) default 0 not null,
    "ID_med_(PK)" NUMBER not null,
    "ID_pront_(PK)" NUMBER,
    "ID_pet_(FK)" NUMBER not null,
    primary key (id),
    constraint ck_exame_removido check (removido in (0,1))
);

create table receita_petcore (
    id NUMBER generated by default as identity,
    nome VARCHAR2(100) not null,
    descricao VARCHAR2(500) not null,
    instrucao VARCHAR2(200) not null,
    data timestamp not null,
    validade date,
    removida NUMBER(1) default 0 not null,
    "ID_med_(PK)" NUMBER not null,
    "ID_pront_(PK)" NUMBER,
    "ID_pet_(FK)" NUMBER not null,
    primary key (id),
    constraint ck_receita_removida check (removida in (0,1))
);

create table relatorio_petcore (
    id NUMBER generated by default as identity,
    observacao VARCHAR2(500),
    data timestamp not null,
    "ID_hist_(PK)" NUMBER not null,
    "ID_med_(PK)" NUMBER not null,
    primary key (id)
);

create table tut_pet_petcore (
    "ID_tut_(FK)" NUMBER not null,
    "ID_pet_(FK)" NUMBER not null,
    primary key ("ID_tut_(FK)", "ID_pet_(FK)")
);

create table rec_medic_petcore (
    "ID_rec_(FK)" NUMBER not null,
    "ID_medic_(FK)" NUMBER not null,
    primary key ("ID_rec_(FK)", "ID_medic_(FK)")
);

create table cli_rel_petcore (
    "ID_cli_(FK)" NUMBER not null,
    "ID_rel_(FK)" NUMBER not null,
    primary key ("ID_cli_(FK)", "ID_rel_(FK)")
);