create table tutor_petcore (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    data_nascimento date,
    telefone varchar(11) not null,
    email varchar(100) not null,
    sexo varchar(1) not null,
    senha varchar(100) not null,
    url_img varchar(255),
    primary key (id)
);

create table medico_petcore (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    data_nascimento date,
    telefone varchar(11) not null,
    email varchar(100) not null,
    sexo varchar(1) not null,
    senha varchar(100) not null,
    especialidade varchar(200) not null,
    url_img varchar(255),
    primary key (id)
);

create table historico_petcore (
    id bigint generated by default as identity,
    data timestamp,
    status tinyint,
    primary key (id)
);

create table pet_petcore (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    especie varchar(100) not null,
    raca varchar(150) not null,
    data_nascimento date,
    pelagem varchar(150) not null,
    porte varchar(25) not null,
    sexo varchar(1) not null,
    status tinyint,
    url_img varchar(255),
    "ID_hist_(FK)" bigint not null,
    primary key (id)
);

create table endereco_petcore (
    id bigint generated by default as identity,
    cep varchar(8) not null,
    complemento varchar(200),
    primary key (id)
);

create table clinica_petcore (
    id bigint generated by default as identity,
    cnpj varchar(14) not null,
    nome varchar(100) not null,
    "ID_end_(FK)" bigint not null,
    primary key (id)
);

create table medicamento_petcore (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    dosagem varchar(15) not null,
    primary key (id)
);

create table prontuario_petcore (
    id bigint generated by default as identity,
    data timestamp not null,
    descricao varchar(500) not null,
    "ID_med_(PK)" bigint not null,
    "ID_hist_(PK)" bigint not null,
    primary key (id)
);

create table exame_petcore (
    id bigint generated by default as identity,
    nome_ex varchar(100) not null,
    data timestamp,
    tp_ex varchar(100) not null,
    removido boolean not null default false,
    "ID_med_(PK)" bigint not null,
    "ID_pront_(PK)" bigint,
    "ID_pet_(FK)" bigint not null,
    primary key (id)
);

create table receita_petcore (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    descricao varchar(500) not null,
    instrucao varchar(200) not null,
    data timestamp not null,
    validade date,
    removida boolean not null default false,
    "ID_med_(PK)" bigint not null,
    "ID_pront_(PK)" bigint,
    "ID_pet_(FK)" bigint not null,
    primary key (id)
);

create table relatorio_petcore (
    id bigint generated by default as identity,
    observacao varchar(500),
    data timestamp not null,
    "ID_hist_(PK)" bigint not null,
    "ID_med_(PK)" bigint not null,
    primary key (id)
);

create table tut_pet_petcore (
    "ID_tut_(FK)" bigint not null,
    "ID_pet_(FK)" bigint not null,
    primary key ("ID_tut_(FK)", "ID_pet_(FK)")
);

create table rec_medic_petcore (
    "ID_rec_(FK)" bigint not null,
    "ID_medic_(FK)" bigint not null,
    primary key ("ID_rec_(FK)", "ID_medic_(FK)")
);

create table cli_rel_petcore (
    "ID_cli_(FK)" bigint not null,
    "ID_rel_(FK)" bigint not null,
    primary key ("ID_cli_(FK)", "ID_rel_(FK)")
);
